// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADFKPvebCq393-htZiY33hpudqSwYZhqw',
    appId: '1:1061114238759:web:aeda4b0e148e85939cfb02',
    messagingSenderId: '1061114238759',
    projectId: 'chatting-b0ee6',
    authDomain: 'chatting-b0ee6.firebaseapp.com',
    storageBucket: 'chatting-b0ee6.appspot.com',
    measurementId: 'G-0HF8NZ1C5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd7I9i2UbY-fRqXrR2yoXBQg2rUt-TV6c',
    appId: '1:1061114238759:android:879a4dd8222ac8a19cfb02',
    messagingSenderId: '1061114238759',
    projectId: 'chatting-b0ee6',
    storageBucket: 'chatting-b0ee6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQXm2RE1NGm741M-vMAyX87YW6Zqg13F0',
    appId: '1:1061114238759:ios:567f698b623af4229cfb02',
    messagingSenderId: '1061114238759',
    projectId: 'chatting-b0ee6',
    storageBucket: 'chatting-b0ee6.appspot.com',
    iosClientId: '1061114238759-nmk70qpj18jg36m7btcuim7d730echfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chating',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQXm2RE1NGm741M-vMAyX87YW6Zqg13F0',
    appId: '1:1061114238759:ios:df7c9c3f536a4fe99cfb02',
    messagingSenderId: '1061114238759',
    projectId: 'chatting-b0ee6',
    storageBucket: 'chatting-b0ee6.appspot.com',
    iosClientId: '1061114238759-q96svtrlce58b7bgac8ck05t4fet2lda.apps.googleusercontent.com',
    iosBundleId: 'com.example.chating.RunnerTests',
  );
}
